package piratesproject.enums;

public enum RequestTypesEnum {
    USERSTABLE,
    REGISTER,
    LOGIN,
    GAMEMOVE,
    INVITATION,
    START_SENDING,
    RECIEVE_INVITATION,
    CONFIRM_INVITATION,
    CREATE_ROOM,
    EXIT,
    AVALIBALE
    ,UPDATESCORE
    ,UPDATEGAMEPLAYED
    ,UPDATEPASSSWORD
    ,CANCEL_INVITATION,
    SEND_CANCEL_INVITATION
}
